version: '3.8'

services:
  db:
    image: postgres:16.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pec_gardez_database
      - POSTGRES_USER=pec_gardez_default_user
      - POSTGRES_PASSWORD=abcdqñ
    expose:
      - 5432
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 django_blog_backend.wsgi
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_NAME=pec_gardez_database
      - POSTGRES_USER=pec_gardez_default_user
      - POSTGRES_PASSWORD=abcdqñ
    depends_on:
      - db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
