version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 django_blog_backend.wsgi
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
