services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pec_gardez_database
      - POSTGRES_USER=pec_gardez_default_user
      - POSTGRES_PASSWORD=abcdqñ
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_NAME=pec_gardez_database
      - POSTGRES_USER=pec_gardez_default_user
      - POSTGRES_PASSWORD=abcdqñ
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  postgres_data:
