# Generated by Django 3.2.22 on 2023-10-31 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('usd', 'USD (US Dollar)'), ('eur', 'EUR (Euro)'), ('ved', 'VED (Bolivar)')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=50)),
                ('owner_identification', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_image', models.URLField(max_length=255)),
                ('resume', models.TextField()),
                ('time_zone', models.CharField(max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('internal_writer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('time_in_minutes', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_owner', to='api.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(max_length=255)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pay_method')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_info')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='The Book title', max_length=50)),
                ('principal_image', models.URLField(max_length=255)),
                ('resume', models.TextField(default='Default text')),
                ('download_url', models.URLField(max_length=255)),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('writers', models.ManyToManyField(to='api.Writer')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='The Article title', max_length=50)),
                ('principal_image', models.URLField(max_length=255)),
                ('content', models.TextField(default='An article')),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('writers', models.ManyToManyField(to='api.Writer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_url', models.URLField(max_length=255)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment_type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='api.user_info')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_user', to='api.user_info')),
                ('pay_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.slot')),
            ],
        ),
    ]
