# Generated by Django 3.2.19 on 2023-08-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_writer_internal_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='resume',
            field=models.TextField(default='Default text'),
        ),
    ]
