# Generated by Django 3.2.22 on 2023-10-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pay_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.user_info'),
        ),
    ]
