# Generated by Django 3.2.22 on 2023-10-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231014_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_owner', to='api.user_info'),
            preserve_default=False,
        ),
    ]
